### ISSUE TITLE
Extra inferred generics causes `never` path on types

### ISSUE THREAD

**Issue by tmikeschu** [biowaffeln/zustand-middleware-xstate#2]
Hello! Thanks for your work 😄 My types don't propagate through the `xstate()` call because of the extra inferred generics `_A`, `_B`, and `_C`. What's the story behind those? When I copy the code from `lib/xstate.ts` and just deleted those and the three extra `any`s in the `M extends StateMachine` line, it works like a charm.

https://github.com/biowaffeln/zustand-middleware-xstate/blob/master/lib/xstate.ts#L10-L12

**Comment by biowaffeln** [comment]
Hey man! What version of xstate are you using? I think I made these changes so that the types were compatible with v4.30.0, perhaps you're using an older version?

**Comment by tmikeschu** [comment]
Ah yeah that must be it, thanks! `4.15.4`. I'll try an upgrade!
