### ISSUE TITLE
update for use with zustand version 4 and newer npm version

### ISSUE THREAD

**Issue by leeahoward** [biowaffeln/zustand-middleware-xstate#3]
I am currently using this with zustand v 4.1.1 and it seems to work, but I get a peer dependency error when installing(with npm 8.19.2 or greater). 

Is this package compatible with zustand 4 and if so can the dependencies be updated so we don't get these warnings with the newer versions of npm? 

npm ERR! While resolving: zustand-middleware-xstate@1.1.1
npm ERR! Found: zustand@4.1.1
npm ERR! node_modules/zustand
npm ERR!   zustand@"^4.1.1" from the root project
npm ERR!   peer zustand@"^3.5.7" from zustand-middleware-xstate@1.1.1
npm ERR!   node_modules/zustand-middleware-xstate
npm ERR!     zustand-middleware-xstate@"^1.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps

npm: '8.19.2',
node: '16.18.1'
"zustand": "^4.1.1",
"zustand-middleware-xstate": "^1.1.1"

I realized this was only happening on certain installations and I can avoid the error by reverting to npm 8.5.4.

**Comment by biowaffeln** [comment]
Thanks for bringing this to my attention! Just published a new major version that has Zustand v4 as a peer dependency
