### ISSUE TITLE
Update for newer xstate version

### ISSUE THREAD

**Issue by Grimthul** [biowaffeln/zustand-middleware-xstate#7]
xState has a new v5, that has some breaking changes https://stately.ai/docs/migration e.g. the onTransition function, types of the StateMachine, Actor instead of Interpreter.

**Comment by Grimthul** [comment]
Created PR https://github.com/biowaffeln/zustand-middleware-xstate/pull/8 as a working example with xState v5, the API changed a lot. 
If you would like to keep intelisense for States on the lightMachine, I think an enum should be used, I did not find a convenient way to pass the type to the xstate's setup function

**Comment by biowaffeln** [comment]
Thanks so much for the PR! Just published a new version
