### ISSUE TITLE
"types" missing in package.json "exports"

### ISSUE THREAD

**Issue by Grimthul** [biowaffeln/zustand-middleware-xstate#9]
When trying to import the xstate to my project I get an TS error 
`Could not find a declaration file for module 'zustand-middleware-xstate'. '...' implicitly has an 'any' type.
  There are types at '...', but this result could not be resolved when respecting package.json "exports". The 'zustand-middleware-xstate' library may need to update its package.json or typings.ts(7016)`
Tried cleaning and re-installing node_modules, but it's probably because of the missing "types" in "exports" in package.json according to this SO:
https://stackoverflow.com/questions/76211877/the-xxxx-library-may-need-to-update-its-package-json-or-typings-ts

**Comment by biowaffeln** [comment]
You're right! Apparently that was a breaking change in TypeScript 4.7, just released a new version that fixes it
